# Site settings
title: "Praneet Bachheti's Resume"
description: "Resume hosting via GitHub Pages site."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "false"
resume_name:                    "Anoop Kapoor"
resume_title:                   "Principal Software Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "anoopskapoor@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "408-817-0844"
resume_contact_address:         "San Francisco Bay Area"

resume_header_contact_info:     "anoopskapoor@gmail.com • 408-817-0844 • San Francisco Bay Area"
display_header_contact_info:    "true"

resume_header_intro: "<p><li> Passionate technical leader in building innovative and challenging software solutions for networking and security products.   </li> <li>Experience in SDN, distributed systems,networking/platform infrastructure, cloud native architecture, machine learning, Kubernetes and automation.</li> <li>Ability to lead complex projects from concept to delivery. Goal-oriented self-
motivated individual with strong problem solving skills.</li> <li>Proficient in Developing new systems, solutions, design and implementations.</li></p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           true
resume_section_associations:    false
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  #resume_github_url:            "https://github.com/praneetb"
  #resume_twitter_url:           "insert your Instagram URL here"
  #resume_dribbble_url:          "insert your Instagram URL here"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/anoop-kapoor-aba73a15/"
  # resume_instagram_url:         "insert your Instagram URL here"
  #resume_website_url:           "http://praneetb.github.io"
  #resume_medium_url:            "insert your Instagram URL here"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
